//
//  PlannedSet.swift
//  SharedModels
//
//  Created by Sebastian Sciuba on 13/05/2026.
//

import Foundation

/// A single prescribed set from a workout plan.
///
/// Generated by the AI scan layer (`ClaudeStrategy` / `ExtractedWorkout+Mapper`)
/// from per-set data returned by the LLM. Used by `SummaryFeature` to pre-populate
/// `SetEntry` instances in `SetInputView` so the user only has to fill in the actual
/// weight per set (and adjust reps if needed).
///
/// `suggestedWeight` is non-nil only when the plan specified an explicit weight in kg
/// (e.g. `"@ 60kg"`). Percent-based prescriptions (e.g. `"@ 50-60%"`) and bodyweight
/// (`"BW"`) leave it nil — the user enters the weight manually.
public struct PlannedSet: Sendable, Equatable, Codable {
    public let reps: Int
    public let suggestedWeight: Double?

    public init(reps: Int, suggestedWeight: Double? = nil) {
        self.reps = reps
        self.suggestedWeight = suggestedWeight
    }
}
