//
//  MovementDetailsFeature+State.swift
//  StepTrackerTCA
//
//  Created by Sebastian Sciuba on 06/04/2025.
//


import ComposableArchitecture
import Foundation

/// Implementation of `MovementDetailsFeature` state
extension MovementDetailsFeature {
    
    /// Represents the state for the `MovementDetailsFeature`.
    @ObservableState
    struct State {
        
        // MARK: - Properties
        
        /// The name of the movement currently being displayed or filtered by.
        let movement: String
        
        /// An array of `GoalInterval` representing the intervals between workout goals.
        /// This array is populated after the `.checkGoals` action is triggered.
        /// - Note: This will be empty if less than two goals are provided.
        var goalIntervals: [GoalInterval] = []
        
        /// The complete set of movements and goals for a particular workout type.
        /// This value is provided by the parent feature and is filtered as needed.
        var selectedMovement: GroupedMovement
        
        ///
        var selectedPoint: WorkoutMeasurement?
        
        ///
        var rawSelectedDate: Date?
        
        /// A filtered version of `selectedMovement` that only includes data for the specific exercise (`movement`).
        /// This value is generated by the `.filterByMovement` action.
        /// - Note: If filtering fails or is not required, this value may be `nil`.
        var filteredMovement: GroupedMovement? = nil
        
        // MARK: - Destination
        
        /// destination from MovementDetailsFeature
        @Presents var destination: Destination.State?
    }
    
}
