//
//  ExtractedWorkout.swift
//  SharedModels
//
//  Created by Sebastian Sciuba on 11/02/2026.
//

import Foundation

// MARK: - ExtractedWorkout

/// A structured workout extracted from OCR text, enriched by Claude API.
///
/// This is the RESPONSE model from Claude API - contains parsed workout sections
/// (warmup, strength, conditioning, etc.) along with AI-generated metadata
/// like workout name and estimated duration.
///
/// Note: The raw OCR text is stored separately in State.extractedText (editable by user).
public struct ExtractedWorkout: Sendable, Equatable, Codable {

    /// Workout name generated by Claude (e.g., "Clean & Jerk + AMRAP").
    public let name: String

    /// Workout date in ISO8601 format "yyyy-MM-dd" (e.g., "2026-02-15").
    /// Optional - Claude may not find a date in the OCR text. Falls back to today's date when converted to TrainingSession.
    public let date: String?

    /// Total estimated duration in minutes (sum of all sections: warmup + workouts + cooldown).
    public let totalEstimatedMinutes: Int

    /// Parsed workout sections in order: warmup, strength/conditioning, cooldown.
    /// Each section contains exercises, time caps, rounds, and other metadata.
    public let sections: [WorkoutSection]

    public init(
        name: String,
        date: String?,
        totalEstimatedMinutes: Int,
        sections: [WorkoutSection]
    ) {
        self.name = name
        self.date = date
        self.totalEstimatedMinutes = totalEstimatedMinutes
        self.sections = sections
    }
}

// MARK: - SectionType

/// The type of a workout section.
public enum SectionType: String, Sendable, Equatable, Codable {

    /// Warmup section - mobility, activation, light cardio (typically 10-20 minutes).
    case warmup

    /// Strength section - heavy lifting with set schemes (e.g., "5×5 @ 80%").
    case strength

    /// Conditioning section - AMRAP, For Time, EMOM workouts with bodyweight or lighter loads.
    case conditioning

    /// Transition section - brief rest/instructions between main workout blocks.
    case transition

    /// Cooldown section - stretching, mobility, recovery work (typically 5-10 minutes).
    case cooldown
}

// MARK: - WorkoutSection

/// A single section within an extracted workout.
public struct WorkoutSection: Sendable, Equatable, Codable {

    /// The section type (warmup, strength, conditioning, transition, or cooldown).
    public let type: SectionType

    /// Section name/identifier (e.g., "WOD 1", "Strength", "AMRAP 10").
    /// Optional - some sections may not have explicit names.
    public let name: String?

    /// Duration in minutes for time-based sections (warmup/cooldown).
    /// Nil for workout sections with time caps or rounds.
    public let durationMinutes: Int?

    /// Detailed description or instructions for this section.
    /// Used for warmup/cooldown to explain movements, mobility work, etc.
    public let description: String?

    /// Time cap in minutes for timed workouts (e.g., "12 min cap" for AMRAP).
    /// Nil for untimed sections like strength.
    public let timeCapMinutes: Int?

    /// Number of rounds or workout format (e.g., "5", "AMRAP", "EMOM").
    /// Can be numeric string ("5") or format descriptor ("AMRAP 10").
    public let rounds: String?

    /// List of exercises in this section.
    /// Nil for warmup/cooldown sections (description field used instead).
    public let exercises: [ExtractedExercise]?

    /// Additional notes or scaling options for this section.
    public let notes: String?

    public init(
        type: SectionType,
        name: String? = nil,
        durationMinutes: Int? = nil,
        description: String? = nil,
        timeCapMinutes: Int? = nil,
        rounds: String? = nil,
        exercises: [ExtractedExercise]? = nil,
        notes: String? = nil
    ) {
        self.type = type
        self.name = name
        self.durationMinutes = durationMinutes
        self.description = description
        self.timeCapMinutes = timeCapMinutes
        self.rounds = rounds
        self.exercises = exercises
        self.notes = notes
    }

    // MARK: - Custom Decoding

    private enum CodingKeys: String, CodingKey {
        case type, name, durationMinutes, description, timeCapMinutes, rounds, exercises, notes
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        // Decode type as String and convert to SectionType enum
        let typeString = try container.decode(String.self, forKey: .type)
        self.type = SectionType(rawValue: typeString) ?? .warmup

        self.name = try container.decodeIfPresent(String.self, forKey: .name)
        self.durationMinutes = try container.decodeIfPresent(Int.self, forKey: .durationMinutes)
        self.description = try container.decodeIfPresent(String.self, forKey: .description)
        self.timeCapMinutes = try container.decodeIfPresent(Int.self, forKey: .timeCapMinutes)
        self.rounds = try container.decodeIfPresent(String.self, forKey: .rounds)
        self.exercises = try container.decodeIfPresent([ExtractedExercise].self, forKey: .exercises)
        self.notes = try container.decodeIfPresent(String.self, forKey: .notes)
    }
}

// MARK: - ExtractedExercise

/// An exercise extracted from OCR text.
public struct ExtractedExercise: Sendable, Equatable, Codable {

    /// Exercise name as extracted from OCR (e.g., "clean and jerk", "pull-ups", "rest").
    /// Mapped to ExerciseType enum via aliases during conversion to TrainingSession.
    public let name: String

    /// Numeric quantity for this exercise (e.g., 16 reps, 400 meters, 180 seconds).
    /// The meaning depends on `unit` field.
    public let reps: Int?

    /// Unit for the numeric quantity. Determines which ExerciseTarget case is used.
    /// - "reps" → ExerciseTarget.reps (default)
    /// - "seconds" → ExerciseTarget.seconds
    /// - "minutes" → ExerciseTarget.minutes
    /// - "meters" → ExerciseTarget.meters
    /// - "calories" → ExerciseTarget.calories
    /// - "laps" → ExerciseTarget.laps
    public let unit: String?

    /// Set schemes for strength exercises (e.g., 4×5 @ 50-60%, 3×4 @ 60-70%).
    /// Nil for AMRAP/conditioning exercises that use simple reps.
    public let sets: [ExerciseSet]?

    /// Scaling options or weight configurations (e.g., "24/16 kg", "RX: 95/65 lbs").
    /// Parsed into WeightConfiguration during conversion to TrainingSession.
    public let scalingOptions: String?

    public init(
        name: String,
        reps: Int? = nil,
        unit: String? = nil,
        sets: [ExerciseSet]? = nil,
        scalingOptions: String? = nil
    ) {
        self.name = name
        self.reps = reps
        self.unit = unit
        self.sets = sets
        self.scalingOptions = scalingOptions
    }
}

// MARK: - ExerciseSet

/// A single set within an exercise, with optional intensity and rest info.
///
/// Used for strength exercises (e.g., "4×5 @ 50-60%").
/// Sets are converted to a human-readable string and stored in `ExerciseSession.info`.
public struct ExerciseSet: Sendable, Equatable, Codable {

    /// Set number within the exercise (1-indexed).
    public let setNumber: Int

    /// Number of reps for this set (e.g., 5 in "4×5").
    /// Optional - Claude may return null for unknown reps (e.g., "MAX reps", "AMRAP").
    /// Sets with null reps are filtered out during conversion to TrainingSession.
    public let reps: Int?

    /// Intensity as percentage or weight (e.g., "50-60%", "80kg", "bodyweight").
    /// Used to group sets into schemes (sets with same reps + intensity = one scheme).
    public let intensity: String?

    /// Rest period between sets in seconds (e.g., 90 for "90 sec rest").
    /// Rarely extracted - most workout plans don't specify rest periods explicitly.
    public let restSeconds: Int?

    public init(
        setNumber: Int,
        reps: Int?,
        intensity: String? = nil,
        restSeconds: Int? = nil
    ) {
        self.setNumber = setNumber
        self.reps = reps
        self.intensity = intensity
        self.restSeconds = restSeconds
    }
}

